name: Build and deploy email-watch-serverless-refresh

permissions:
  id-token: write
  contents: read

env:
  NAME: "email-watch-serverless-refresh"
  VERSION: "1.0.0-SNAPSHOT"

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo to virtual machine
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      # 2. Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Build the JAR with Maven and run unit tests
      - name: Build JAR
        run: mvn clean package
      
      # 4. Authenticate with GCP
      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      # 5. Deploy Cloud Function
      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy email-watch-serverless-refresh \
            --entry-point=com.avasileuski.RefreshGmailWatch \
            --runtime=java21 \
            --trigger-http \
            --region=europe-central2 \
            --source=. \
            --allow-unauthenticated
